name: Node.js CI
'on':
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: '.nvmrc'
      - run: npm clean-install
      - run: npm test

  automerge:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GH_PAT }}
