name: Node.js CI
'on':
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          cache: npm
          node-version-file: '.nvmrc'
      - uses: bahmutov/npm-install@v1
      - run: npm test

  automerge:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
